### ISSUE TITLE
Missing `extraction_model` property in `ScrapeConfigOptions` in version 0.6.8

### ISSUE THREAD

**Issue by paulosalvatore** [scrapfly/typescript-scrapfly#12]
## Description

Hello, team!

I recently noticed that in version **0.6.8** of the Scrapfly TypeScript library, the `ScrapeConfigOptions` configuration object does not have the `extraction_model` property. This property is essential for certain scraping configurations, and its absence limits some functionalities we depend on.

## Steps to Reproduce

1. Install version 0.6.8 of the Scrapfly library.
2. Attempt to set `extraction_model` in the `ScrapeConfigOptions` object.
3. Observe that TypeScript does not recognize `extraction_model` as a valid property.

## Expected Behavior

The `ScrapeConfigOptions` object should include `extraction_model` as a configurable property.

## Environment

- **Library version**: 0.6.8
- **Language**: TypeScript
- **Node.js version**: v18.20.4

Could you please confirm if this is an oversight, and if so, could it be added in an upcoming release?

Thank you for your hard work and for providing such a useful tool!

![image](https://github.com/user-attachments/assets/1fffa468-caaf-428c-839c-2496d9f74966)

**Comment by dervishmoose** [comment]
I am running into the same issue today using 0.6.8  "Invalid option provided: extraction_model"

Environment
Library version: 0.6.8
Language: TypeScript
Deno ver:?

**Comment by mazen-r** [comment]
Hey @paulosalvatore and @dervishmoose, thanks for reporting this. Yes currently extraction params aren't implemented for the `scrape` action, they are only available in the `extract` action. Extraction params will be supported for the scraper API soon

**Comment by mazen-r** [comment]
Hey @paulosalvatore and @dervishmoose, extraction params are now available for the `scrape` action
