### ISSUE TITLE
Encoding js doesn't always work

### ISSUE THREAD

**Issue by david-moonsift** [scrapfly/typescript-scrapfly#2]
I believe that this applies for any js script that encodes to base64 with more than one `+` or `/`

A decision needs to be made on how to update this file:
[src/utils.ts](https://github.com/scrapfly/typescript-scrapfly/blob/main/src/utils.ts#L1)

Either it could encode to 'base64url' as is possible since node14
Or it should use 'replaceAll' instead of just 'replace' (since node15)
Or write a replace as a regex with global `g` suffix (see https://futurestud.io/tutorials/node-js-string-replace-all-appearances)

More info on base64 chars: https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url

**Comment by Granitosaurus** [comment]
Hey @moonsift thanks for opening the issue! 
I've updated to replace all occurrences of + and / though I couldn't find any utf-8 strings that would produce b64 result with multiples of `+` or `/` characters so I think the impact of this is very minimal. Are you aware of any that we could add to our tests here:
https://github.com/scrapfly/typescript-scrapfly/blob/main/__tests__/utils.test.ts#L9

**Comment by david-moonsift** [comment]
Thanks for the quick fix on this, really appreciated.

Here's some tests for you:

with two "/" characters (seems to be caused by the `?`)
```
const has_env1 = window.env1 ? true : false;
const has_env2 = window.env2 ? true : false;
```

```
Y29uc3QgaGFzX2VudjEgPSB3aW5kb3cuZW52MSA/IHRydWUgOiBmYWxzZTsKY29uc3QgaGFzX2VudjIgPSB3aW5kb3cuZW52MiA/IHRydWUgOiBmYWxzZTs=
```

and with two "+" chatacters:
```
const is_greater_than_1 = 45 >= 5 ? true : false
const is_greater_than_2 = 6435 >= 5 ? true : false
```

```
Y29uc3QgaXNfZ3JlYXRlcl90aGFuXzEgPSA0NSA+PSA1ID8gdHJ1ZSA6IGZhbHNlCmNvbnN0IGlzX2dyZWF0ZXJfdGhhbl8yID0gNjQzNSA+PSA1ID8gdHJ1ZSA6IGZhbHNl
```

Obviously silly examples but as you see it could easily happen.

Thanks again

**Comment by Granitosaurus** [comment]
awesome, added tests with these examples. Thanks @moonsift!
